import http from 'k6/http';
import { check, sleep } from 'k6';
import { Trend, Counter, Rate } from 'k6/metrics';

// Load pre-seeded data generated by k6/seed-k6.ts
const testData = JSON.parse(open('./data/k6-test-data.json'));

// Custom metrics for read and write response time distributions
const readDuration = new Trend('read_duration', true);
const writeDuration = new Trend('write_duration', true);
const bookingConflicts = new Counter('booking_conflicts');
const bookingSuccesses = new Counter('booking_successes');
const errorRate = new Rate('error_rate');

export const options = {
  scenarios: {
    // ─────────────────────────────────────────────────────────────
    // 1. Read Scenario: Constant arrival rate on search + profile
    // ─────────────────────────────────────────────────────────────
    read_traffic: {
      executor: 'constant-arrival-rate',
      rate: 30, // 30 requests per second
      timeUnit: '1s',
      duration: '25s',
      preAllocatedVUs: 15,
      maxVUs: 50,
      exec: 'runReadScenario',
    },

    // ─────────────────────────────────────────────────────────────
    // 2. Write Scenario: Bookings with unique idempotency keys
    // ─────────────────────────────────────────────────────────────
    write_traffic: {
      executor: 'shared-iterations',
      vus: 8,
      iterations: 150,
      maxDuration: '25s',
      startTime: '3s', // Stagger start slightly after reads start
      exec: 'runWriteScenario',
    },
  },

  // Enforce assignment performance NFR thresholds:
  // - p95 < 200ms for reads
  // - p95 < 500ms for writes
  // - < 1% error rate
  thresholds: {
    'read_duration': ['p(95)<200', 'p(99)<400'],
    'write_duration': ['p(95)<500', 'p(99)<800'],
    'http_req_failed': ['rate<0.01'],
    'error_rate': ['rate<0.01'],
  },
};

const BASE_URL = __ENV.BASE_URL || testData.baseUrl || 'http://localhost:3000';

/**
 * UUID v4 generator for k6 JavaScript runtime
 */
function uuidv4() {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function (c) {
    const r = (Math.random() * 16) | 0;
    const v = c === 'x' ? r : (r & 0x3) | 0x8;
    return v.toString(16);
  });
}

/**
 * Read Scenario: Alternates between Full-text/Trigram search and Doctor Profile lookup
 */
export function runReadScenario() {
  const isSearch = Math.random() > 0.4;

  if (isSearch) {
    const term = testData.searchTerms[Math.floor(Math.random() * testData.searchTerms.length)];
    const url = `${BASE_URL}/search/doctors?q=${encodeURIComponent(term)}&limit=10`;

    const res = http.get(url, {
      headers: {
        Accept: 'application/json',
        Authorization: `Bearer ${testData.patientToken}`,
      },
      tags: { type: 'read', endpoint: 'search' },
    });

    readDuration.add(res.timings.duration);
    const passed = check(res, {
      'search status is 200': (r) => r.status === 200,
      'search returns results array': (r) => {
        try {
          const body = JSON.parse(r.body);
          return Array.isArray(body.results);
        } catch {
          return false;
        }
      },
    });

    errorRate.add(!passed);
  } else {
    const docId = testData.doctorIds[Math.floor(Math.random() * testData.doctorIds.length)];
    const url = `${BASE_URL}/doctors/${docId}`;

    const res = http.get(url, {
      headers: {
        Accept: 'application/json',
        Authorization: `Bearer ${testData.patientToken}`,
      },
      tags: { type: 'read', endpoint: 'profile' },
    });

    readDuration.add(res.timings.duration);
    const passed = check(res, {
      'profile status is 200': (r) => r.status === 200,
      'profile has doctor data': (r) => {
        try {
          const body = JSON.parse(r.body);
          return body.data && body.data.id === docId;
        } catch {
          return false;
        }
      },
    });

    errorRate.add(!passed);
  }
}

/**
 * Write Scenario: Atomic Consultation Booking with unique Idempotency-Key
 */
export function runWriteScenario() {
  // Select a unique slot index deterministically per iteration
  const slotIndex = __ITER % testData.slotIds.length;
  const slotId = testData.slotIds[slotIndex];
  const idempotencyKey = uuidv4();

  const payload = JSON.stringify({
    slotId: slotId,
    reason: `k6 automated stress test booking iteration ${__ITER}`,
  });

  const params = {
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${testData.patientToken}`,
      'Idempotency-Key': idempotencyKey,
    },
    tags: { type: 'write', endpoint: 'book_consultation' },
    responseCallback: http.expectedStatuses(201, 409),
  };

  const res = http.post(`${BASE_URL}/consultations`, payload, params);

  writeDuration.add(res.timings.duration);

  if (res.status === 201) {
    bookingSuccesses.add(1);
    check(res, {
      'booking created status is 201': (r) => r.status === 201,
      'booking has consultation id': (r) => {
        try {
          const b = JSON.parse(r.body);
          return !!b.id;
        } catch {
          return false;
        }
      },
    });
    errorRate.add(0);
  } else if (res.status === 409) {
    // 409 is a valid concurrency conflict response under contention
    bookingConflicts.add(1);
    errorRate.add(0);
  } else {
    // Any other response code (5xx, 400, etc.) counts as an unexpected error
    errorRate.add(1);
    check(res, {
      'booking unexpectedly failed': () => false,
    });
  }

  // Small pacing interval between iterations for realistic write concurrency
  sleep(0.05);
}
