{
 "title": "RED Metrics per Route",
 "tags": [
  "amrutam",
  "red",
  "api"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Request Rate (Rate - req/s) by Route",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m])) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "HTTP Error Rate (Errors - 5xx / 4xx req/s) by Route",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status_code=~\"5..\"}[1m])) by (route)",
     "legendFormat": "5xx {{route}}"
    },
    {
     "expr": "sum(rate(http_requests_total{status_code=~\"4..\"}[1m])) by (route)",
     "legendFormat": "4xx {{route}}"
    }
   ]
  },
  {
   "title": "Latency p95 Duration (Duration - seconds) by Route",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, route))",
     "legendFormat": "p95 {{route}}"
    }
   ]
  },
  {
   "title": "Latency p50 & p99 Duration by Route",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, route))",
     "legendFormat": "p50 {{route}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, route))",
     "legendFormat": "p99 {{route}}"
    }
   ]
  }
 ]
}